# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50, verbose_name='model')),
                ('model_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='vehicle_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.VehicleDetails'),
        ),
    ]
