# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicledetails_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
