# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='purchased_amount',
            new_name='amount_purchased',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sold_amount',
            new_name='amount_sold',
        ),
        migrations.AddField(
            model_name='invoice',
            name='valuation_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
