# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20171010_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=12)),
                ('amount_purchased', models.PositiveIntegerField()),
                ('expense', models.PositiveIntegerField()),
                ('valuation_amount', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=12)),
                ('amount_sold', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vehicle_detail',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='vehicle_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='vehicle_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='invoicesale',
            name='party_sold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.UserDetails'),
        ),
        migrations.AddField(
            model_name='invoicesale',
            name='purchase_bill_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.InvoicePurchase'),
        ),
        migrations.AddField(
            model_name='invoicepurchase',
            name='party_purchased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.UserDetails'),
        ),
        migrations.AddField(
            model_name='invoicepurchase',
            name='vehicle_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.VehicleDetails'),
        ),
    ]
