# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20171010_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_profit', models.PositiveIntegerField()),
                ('purchase_bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.InvoicePurchase')),
                ('sale_bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.InvoiceSale')),
            ],
        ),
    ]
