# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 09:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_remove_accounting_purchase_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='aadhar_no',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.CharField(default='NOT GIVEN', max_length=200),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='NOT GIVEN', max_length=140),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone_no',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
