# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 19:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_auto_20171012_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('aadhar_no', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('phone_no', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(default='NOT GIVEN', max_length=140)),
                ('address', models.CharField(default='NOT GIVEN', max_length=200)),
                ('is_buyer', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('vehicle_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.VehicleDetails')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='vehicle_detail',
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='party_purchased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.PartyDetails'),
        ),
        migrations.AlterField(
            model_name='invoicesale',
            name='party_sold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.PartyDetails'),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
