# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_auto_20171017_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partydetails',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='partydetails',
            name='last_name',
        ),
    ]
