# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_auto_20171022_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='chassis_no',
            field=models.CharField(default='NA', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='color',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partydetails',
            name='address',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='partydetails',
            name='email',
            field=models.EmailField(default='NA', max_length=140),
        ),
    ]
