# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_auto_20171025_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partydetails',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
