# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_auto_20171025_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partydetails',
            old_name='vehicle_detail',
            new_name='vehicle_sold_detail',
        ),
    ]
