# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_auto_20171025_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepurchase',
            name='bill_no',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='invoicesale',
            name='bill_no',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
