# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_auto_20171025_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepurchase',
            name='vehicle_detail',
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='bill_no',
            field=models.CharField(blank=True, default=vehicles.models.generate_purchase_bill_no, max_length=12),
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 2, 13, 19, 573937)),
        ),
        migrations.AlterField(
            model_name='invoicesale',
            name='bill_no',
            field=models.CharField(blank=True, default=vehicles.models.generate_sale_bill_no, max_length=12),
        ),
    ]
